### ISSUE TITLE
send_binary_mode

### ISSUE THREAD

**Issue by drews256** [mmartinortiz/pyePuck#2]
Any chance anyone can shed light on this error. 

```
  File "/home/andrew/catkin_ws/src/epuck_driver/src/epuck/ePuck.py", line 348, in send_binary_mode
    raise e
struct.error: unpack requires a string argument of length 4
```

I think it has to do with my bluetooth connection. But other information would be great. It seems to only happen when I am attempting to send information to two epucks at the same time over bluetooth. 

Both epucks have the newest firmware. And I have tried connecting to both of them with my internal bluetooth and with an external bluetooth dongle.

**Comment by mmartinortiz** [comment]
The line pointed by the exception does not match with the code uploaded to the repository. I guess that you added/removed some code that I cannot see. Anyway, it seems that you are not receiving data from the robot.

Keep in mind that it was made for the firmware 1.4.2 and 1.4.3. The library is not tested with other versions of the firmware.

**Comment by drews256** [comment]
I am just curious if there was a way to not get the unpack requires a string argument of length 4 error. Which I think has to do with the way data is sent via bluetooth. I know that because of connection problems data can be faulty but my connection completely stops every time I see this error. Is there a better way to handle it? 

It wasn't hard to find on line 322 the code is as follows strictly copy and pasted from your repository. 

```
        # We can read sensors in two ways: Binary Mode and Ascii Mode
        # Ascii mode is slower than Binary mode, therefore, we use
        # Binary mode whenever we can. Not all sensors are available in
        # Binary mode

        def send_binary_mode(parameters):
            # Auxiliar function for sent messages in binary modes
            # Parameters: ('Char to be sent', 'Size of reply waited', 'Format of the teply')

            self._debug('Sending binary message: ', ','.join('%s' % i for i in parameters))
            message = struct.pack(">bb", - ord(parameters[0]), 0)
            self._send(message)
            reply = self._recv()
            while len(reply) < parameters[1]:
                reply += self._recv()
            reply = struct.unpack(parameters[2], reply)

            self._debug('Binary message recived: ', reply)
            return reply
```

**Comment by mmartinortiz** [comment]
Try surrounding the 348 line between a try except statement

``` python
try:
    reply = struct.unpack(parameters[2], reply)
except Exception as e:
   self._debug('Error unpacking parameters:', reply)
   reply = ''
```
